# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EnvDL',
                'doc_host': 'https://DanielKick-USDA.github.io',
                'git_url': 'https://github.com/DanielKick-USDA/EnvDL',
                'lib_path': 'EnvDL'},
  'syms': {'EnvDL.core': {'EnvDL.core.foo': ('core.html#foo', 'EnvDL/core.py')}}}
