# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01.02_g2fc_imputation.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01.02_g2fc_imputation.ipynb 7
# "Iteratively check for and create directories to store output. Ideally this would just be os.mkdirs() but that function is not available in this version of python"
# def ensure_dir_path_exists(dir_path = '../ext_data'):
#     import os
    
#     for i in range(2, len(dir_path.split('/'))+1):
#         path_part = '/'.join(dir_path.split('/')[0:i])
#         if not os.path.exists(path_part):
#             os.mkdir(path_part)
